#encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
CompetitionItem.create(id: 1, name: 'лечебное дело, общий конкурс, бюджет')
CompetitionItem.create(id: 2, name: 'педиатрия, общий конкурс, бюджет')
CompetitionItem.create(id: 3, name: 'стоматолоигя, общий конкурс, бюджет')
CompetitionItem.create(id: 4, name: 'лечебное дело, общий конкурс, внебюджет')
CompetitionItem.create(id: 5, name: 'педиатрия, общий конкурс, внебюджет')
CompetitionItem.create(id: 6, name: 'стоматология, общий конкурс, внебюджет')
CompetitionItem.create(id: 7, name: 'лечебное дело, квота целевого приема')
CompetitionItem.create(id: 8, name: 'педиатрия, квота целевого приема')
CompetitionItem.create(id: 9, name: 'стоматология, квота целевого приема')
CompetitionItem.create(id: 10, name: 'лечебное дело, особое право')
CompetitionItem.create(id: 11, name: 'педиатрия, особое право')
CompetitionItem.create(id: 12, name: 'стоматология, особое право')
CompetitionItem.create(id: 13, name: 'лечебное дело, вне конкурса, бюджет')
CompetitionItem.create(id: 14, name: 'педиатрия, вне конкурса, бюджет')
CompetitionItem.create(id: 15, name: 'стоматология вне конкурса, бюджет')
CompetitionItem.create(id: 16, name: 'лечебное дело, вне конкурса, внебюджет')
CompetitionItem.create(id: 17, name: 'педиатрия, вне конкурса, внебюджет')
CompetitionItem.create(id: 18, name: 'стоматология, вне конкурса, внебюджет')
Campaign.create(id: 1, name: 'Приёмная кампания 2013', year_start: 2013, year_end: 2013, status_id: 1)
EducationForm.create(id: 1, education_form_id: 11, campaign_id: 1)
EducationLevel.create(id: 1, course: 1, education_level_id: 5, campaign_id: 1)
CampaignDate.create(id: 1, course: 1, education_level_id: 5, education_form_id: 11, education_source_id: 14, stage: 1, date_start: '2013-06-20', date_end: '2013-07-25', date_order: '2013-08-05', campaign_id: 1)
CampaignDate.create(id: 2, course: 1, education_level_id: 5, education_form_id: 11, education_source_id: 14, stage: 2, date_start: '2013-06-20', date_end: '2013-07-25', date_order: '2013-08-10', campaign_id: 1)
CampaignDate.create(id: 3, course: 1, education_level_id: 5, education_form_id: 11, education_source_id: 15, stage: nil, date_start: '2013-06-20', date_end: '2013-07-25', date_order: '2013-08-10', campaign_id: 1)
CampaignDate.create(id: 4, course: 1, education_level_id: 5, education_form_id: 11, education_source_id: 16, stage: nil, date_start: '2013-06-20', date_end: '2013-07-25', date_order: '2013-07-30', campaign_id: 1)
AdmissionVolume.create(id: 1, campaign_id: 1, education_level_id: 5, course: 1, direction_id: 438, number_budget_o: 88, number_paid_o: 95, number_target_o: 92)
AdmissionVolume.create(id: 2, campaign_id: 1, education_level_id: 5, course: 1, direction_id: 441, number_budget_o: 88, number_paid_o: 55, number_target_o: 42)
AdmissionVolume.create(id: 3, campaign_id: 1, education_level_id: 5, course: 1, direction_id: 470, number_budget_o: 10, number_paid_o: 25, number_target_o: 5)
CompetitiveGroup.create(id: 1, campaign_id: 1, course: 1, name: 'Лечебное дело')
CompetitiveGroup.create(id: 2, campaign_id: 1, course: 1, name: 'Педиатрия')
CompetitiveGroup.create(id: 3, campaign_id: 1, course: 1, name: 'Стоматология')
CompetitiveGroupItem.create(id: 1, competitive_group_id: 1, education_level_id: 5, direction_id: 438, number_budget_o: 88, number_paid_o: 95, number_target_o: 92)
CompetitiveGroupItem.create(id: 2, competitive_group_id: 2, education_level_id: 5, direction_id: 441, number_budget_o: 88, number_paid_o: 55, number_target_o: 42)
CompetitiveGroupItem.create(id: 3, competitive_group_id: 3, education_level_id: 5, direction_id: 470, number_budget_o: 10, number_paid_o: 25, number_target_o: 5)
TargetOrganization.create(id: 1, competitive_group_id: 1, target_organization_name: 'Департамент здравоохранения Брянской области (лечебное дело)')
TargetOrganization.create(id: 2, competitive_group_id: 1, target_organization_name: 'Департамент здравоохранения Владимирской области (лечебное дело)')
TargetOrganization.create(id: 3, competitive_group_id: 1, target_organization_name: 'Департамент здравоохранения Вологодской области (лечебное дело)')
TargetOrganization.create(id: 4, competitive_group_id: 1, target_organization_name: 'Департамент здравоохранения Ивановской области (лечебное дело)')
TargetOrganization.create(id: 5, competitive_group_id: 1, target_organization_name: 'Департамент здравоохранения Калужской области (лечебное дело)')
TargetOrganization.create(id: 6, competitive_group_id: 1, target_organization_name: 'Департамент здравоохранения Костромской области (лечебное дело)')
TargetOrganization.create(id: 7, competitive_group_id: 1, target_organization_name: 'Департамент здравоохранения Липецкой области (лечебное дело)')
TargetOrganization.create(id: 8, competitive_group_id: 1, target_organization_name: 'Департамент здравоохранения Тульской области (лечебное дело)')
TargetOrganization.create(id: 9, competitive_group_id: 1, target_organization_name: 'Федеральное медико-биологическое агентство (лечебное дело)')
TargetOrganization.create(id: 18, competitive_group_id: 2, target_organization_name: 'Департамент здравоохранения Брянской области (педиатрия)')
TargetOrganization.create(id: 19, competitive_group_id: 2, target_organization_name: 'Департамент здравоохранения Владимирской области (педиатрия)')
TargetOrganization.create(id: 20, competitive_group_id: 2, target_organization_name: 'Департамент здравоохранения Ивановской области (педиатрия)')
TargetOrganization.create(id: 21, competitive_group_id: 2, target_organization_name: 'Департамент здравоохранения Калужской области (педиатрия)')
TargetOrganization.create(id: 22, competitive_group_id: 2, target_organization_name: 'Департамент здравоохранения Костромской области (педиатрия)')
TargetOrganization.create(id: 23, competitive_group_id: 2, target_organization_name: 'Департамент здравоохранения Тульской области (педиатрия)')
TargetOrganization.create(id: 24, competitive_group_id: 2, target_organization_name: 'Федеральное медико-биологическое агентство (педиатрия)')
TargetOrganization.create(id: 25, competitive_group_id: 3, target_organization_name: 'Департамент здравоохранения Ивановской области (стоматология)')
CompetitiveGroupTargetItem.create(id: 155, target_organization_id: 1, education_level_id: 5, number_target_o: 1, direction_id: 438)
CompetitiveGroupTargetItem.create(id: 156, target_organization_id: 2, education_level_id: 5, number_target_o: 26, direction_id: 438)
CompetitiveGroupTargetItem.create(id: 157, target_organization_id: 3, education_level_id: 5, number_target_o: 5, direction_id: 438)
CompetitiveGroupTargetItem.create(id: 158, target_organization_id: 4, education_level_id: 5, number_target_o: 45, direction_id: 438)
CompetitiveGroupTargetItem.create(id: 159, target_organization_id: 5, education_level_id: 5, number_target_o: 2, direction_id: 438)
CompetitiveGroupTargetItem.create(id: 160, target_organization_id: 6, education_level_id: 5, number_target_o: 3, direction_id: 438)
CompetitiveGroupTargetItem.create(id: 161, target_organization_id: 7, education_level_id: 5, number_target_o: 2, direction_id: 438)
CompetitiveGroupTargetItem.create(id: 162, target_organization_id: 8, education_level_id: 5, number_target_o: 3, direction_id: 438)
CompetitiveGroupTargetItem.create(id: 163, target_organization_id: 9, education_level_id: 5, number_target_o: 5, direction_id: 438)
CompetitiveGroupTargetItem.create(id: 164, target_organization_id: 18, education_level_id: 5, number_target_o: 2, direction_id: 441)
CompetitiveGroupTargetItem.create(id: 165, target_organization_id: 19, education_level_id: 5, number_target_o: 12, direction_id: 441)
CompetitiveGroupTargetItem.create(id: 166, target_organization_id: 20, education_level_id: 5, number_target_o: 20, direction_id: 441)
CompetitiveGroupTargetItem.create(id: 167, target_organization_id: 21, education_level_id: 5, number_target_o: 2, direction_id: 441)
CompetitiveGroupTargetItem.create(id: 168, target_organization_id: 22, education_level_id: 5, number_target_o: 3, direction_id: 441)
CompetitiveGroupTargetItem.create(id: 169, target_organization_id: 23, education_level_id: 5, number_target_o: 2, direction_id: 441)
CompetitiveGroupTargetItem.create(id: 170, target_organization_id: 24, education_level_id: 5, number_target_o: 1, direction_id: 441)
CompetitiveGroupTargetItem.create(id: 171, target_organization_id: 25, education_level_id: 5, number_target_o: 5, direction_id: 470)
EntranceTestItem.create(id: 1, entrance_test_type_id: 1, form: 'ЕГЭ', min_score: 36)
EntranceTestItem.create(id: 2, entrance_test_type_id: 1, form: 'ЕГЭ', min_score: 36)
EntranceTestItem.create(id: 3, entrance_test_type_id: 1, form: 'ЕГЭ', min_score: 36)
EntranceTestItem.create(id: 4, entrance_test_type_id: 1, form: 'ЕГЭ', min_score: 36)
EntranceTestItem.create(id: 5, entrance_test_type_id: 1, form: 'ЕГЭ', min_score: 36)
EntranceTestItem.create(id: 6, entrance_test_type_id: 1, form: 'ЕГЭ', min_score: 36)
EntranceTestItem.create(id: 7, entrance_test_type_id: 1, form: 'ЕГЭ', min_score: 36)
EntranceTestItem.create(id: 8, entrance_test_type_id: 1, form: 'ЕГЭ', min_score: 36)
EntranceTestItem.create(id: 9, entrance_test_type_id: 1, form: 'ЕГЭ', min_score: 36)
EntranceTestSubject.create(id: 1, subject_id: 1, entrance_test_item_id: 1)
EntranceTestSubject.create(id: 3, subject_id: 1, entrance_test_item_id: 4)
EntranceTestSubject.create(id: 4, subject_id: 1, entrance_test_item_id: 7)
EntranceTestSubject.create(id: 5, subject_id: 4, entrance_test_item_id: 2)
EntranceTestSubject.create(id: 6, subject_id: 4, entrance_test_item_id: 5)
EntranceTestSubject.create(id: 7, subject_id: 4, entrance_test_item_id: 8)
EntranceTestSubject.create(id: 8, subject_id: 11, entrance_test_item_id: 3)
EntranceTestSubject.create(id: 9, subject_id: 11, entrance_test_item_id: 6)
EntranceTestSubject.create(id: 10, subject_id: 11, entrance_test_item_id: 9)
Campaign.create(name: 'Приёмная кампания 2014 специалитет', year_start: 2014, year_end: 2014, status_id: 1)
EducationForm.create(education_form_id: 11, campaign_id: 2)
EducationLevel.create(course: 1, education_level_id: 5, campaign_id: 2)
CampaignDate.create(course: 1, education_level_id: 5, education_form_id: 11, education_source_id: 14, stage: 1, date_start: '2014-06-20', date_end: '2014-07-25', date_order: '2014-08-05', campaign_id: 2)
CampaignDate.create(course: 1, education_level_id: 5, education_form_id: 11, education_source_id: 14, stage: 2, date_start: '2014-06-20', date_end: '2014-07-25', date_order: '2014-08-11', campaign_id: 2)
CampaignDate.create(course: 1, education_level_id: 5, education_form_id: 11, education_source_id: 15, stage: nil, date_start: '2014-06-20', date_end: '2014-07-25', date_order: '2014-08-15', campaign_id: 2)
CampaignDate.create(course: 1, education_level_id: 5, education_form_id: 11, education_source_id: 16, stage: nil, date_start: '2014-06-20', date_end: '2014-07-25', date_order: '2014-07-31', campaign_id: 2)
AdmissionVolume.create(campaign_id: 2, education_level_id: 5, course: 1, direction_id: 438, number_budget_o: 74, number_paid_o: 70, number_target_o: 92, number_quota_o: 19)
AdmissionVolume.create(campaign_id: 2, education_level_id: 5, course: 1, direction_id: 441, number_budget_o: 52, number_paid_o: 50, number_target_o: 65, number_quota_o: 13)
AdmissionVolume.create(campaign_id: 2, education_level_id: 5, course: 1, direction_id: 470, number_budget_o: 8, number_paid_o: 20, number_target_o: 10, number_quota_o: 2)
CompetitiveGroup.create(campaign_id: 2, course: 1, name: 'Специалитет')